test:
    name: supplyflow-benchmark
    description: test benchmark
    workers:
      type: local
      number: 2
    rounds:
      - label: supplyflow test
        description: supplyflow benchmark
        txDuration: 60
        rateControl: 
          type: "fixed-rate"
          opts:
            tps: 25
            #transactionLoad: 300
        workload:
          module: /hyperledger/caliper/workspace/app/callback/app.js
          arguments:
            contractId: supplyflow
            randomSeed: 5000000
            userID: Admin@distillery.supply.com

monitor:
  type:
  - prometheus
  prometheus:
    url: "http://localhost:9090"
    push_url: "http://localhost:9100"
  metrics:
    ignore: [prometheus, pushGateway, caadvisor, grafana, node-exporter]
    include: [Memory(avg), CPU%(avg)]
    charting:
    bar:
      metrics: [Memory(avg), CPU%(avg)]
    polar:
      metrica: [all]

