---
"name": "supplychain"
"x-type": "hlfv1"
"version": "1.0.0"
"channels":
  "supplychain":
    "orderers":
    - "orderer1.supply.com"
    - "orderer2.supply.com"
    - "orderer3.supply.com"
    "peers":
    - "peer1.distillery.supply.com"
    - "peer2.distillery.supply.com"
    - "peer1.producer1.supply.com"
"organizations":
  "distillery.supply.com":
    "mspid": "distillery-supply-com"
    "peers":
    - "peer1.distillery.supply.com"
    - "peer2.distillery.supply.com"
    "orderers": []
    "certificateAuthorities":
    - "ca1.distillery.supply.com"
  "producer1.supply.com":
    "mspid": "producer1-supply-com"
    "peers":
    - "peer1.producer1.supply.com"
    "orderers": []
    "certificateAuthorities":
    - "ca1.producer1.supply.com"
  "supply.com":
    "mspid": "supply-com"
    "peers": []
    "orderers":
    - "orderer1.supply.com"
    - "orderer2.supply.com"
    - "orderer3.supply.com"

"orderers":
  "orderer1.supply.com":
    "url": "grpcs://orderer1.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer1.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICnDCCAkKgAwIBAgIUYW3vJjNmOu4+/csaWmMOGmWBZjQwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDQyNzA5NTM1MVoXDTMyMDQyNDA5NTM1MVowaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7H07q1iJH2HBFYzNzXxSfuVd\nmMAAGRMdNd+J+DiMD9tM1mb29sL7snbbqUIzKekzZOvkVee6lTeOukZxlQwdGaOB\nyTCBxjAdBgNVHQ4EFgQU3Lhm9am4JSAYGgVcGhAT8JDpMAMwHwYDVR0jBBgwFoAU\n3Lhm9am4JSAYGgVcGhAT8JDpMAMwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQmCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiEA6EreS1HdgDAdligkthFiRb23\nBZlRU9x0FW4fe0n3I6cCIA/vRXs5QZwBl5OxuIbNPi6VR42VGt5nCxX3JAqoLXwP\n-----END CERTIFICATE-----"
  "orderer2.supply.com":
    "url": "grpcs://orderer2.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer2.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICnDCCAkKgAwIBAgIUYW3vJjNmOu4+/csaWmMOGmWBZjQwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDQyNzA5NTM1MVoXDTMyMDQyNDA5NTM1MVowaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7H07q1iJH2HBFYzNzXxSfuVd\nmMAAGRMdNd+J+DiMD9tM1mb29sL7snbbqUIzKekzZOvkVee6lTeOukZxlQwdGaOB\nyTCBxjAdBgNVHQ4EFgQU3Lhm9am4JSAYGgVcGhAT8JDpMAMwHwYDVR0jBBgwFoAU\n3Lhm9am4JSAYGgVcGhAT8JDpMAMwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQmCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiEA6EreS1HdgDAdligkthFiRb23\nBZlRU9x0FW4fe0n3I6cCIA/vRXs5QZwBl5OxuIbNPi6VR42VGt5nCxX3JAqoLXwP\n-----END CERTIFICATE-----"
  "orderer3.supply.com":
    "url": "grpcs://orderer3.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer3.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICnDCCAkKgAwIBAgIUYW3vJjNmOu4+/csaWmMOGmWBZjQwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDQyNzA5NTM1MVoXDTMyMDQyNDA5NTM1MVowaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7H07q1iJH2HBFYzNzXxSfuVd\nmMAAGRMdNd+J+DiMD9tM1mb29sL7snbbqUIzKekzZOvkVee6lTeOukZxlQwdGaOB\nyTCBxjAdBgNVHQ4EFgQU3Lhm9am4JSAYGgVcGhAT8JDpMAMwHwYDVR0jBBgwFoAU\n3Lhm9am4JSAYGgVcGhAT8JDpMAMwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQmCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiEA6EreS1HdgDAdligkthFiRb23\nBZlRU9x0FW4fe0n3I6cCIA/vRXs5QZwBl5OxuIbNPi6VR42VGt5nCxX3JAqoLXwP\n-----END CERTIFICATE-----"

"peers":
  "peer1.distillery.supply.com":
    "url": "grpcs://peer1.distillery.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer1.distillery.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC4jCCAoigAwIBAgIUYGvCbUW+jyvuRR5EIOjgAH4a+I8wCgYIKoZIzj0EAwIw\nfzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xJTAjBgNV\nBAMMHHRsc2NhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwNDI3MDk1MjQ4\nWhcNMzIwNDI0MDk1MjQ4WjB/MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGgg\nQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnku\nc3VwcGx5LmNvbTElMCMGA1UEAwwcdGxzY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNv\nbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDE0EjSWmnNu6eaoVtIZ9P0eUucJ\n3MAHkwpx17ltjgXJcJ5UVgcJ7cjzuavxB/AS+kLblf/ajwGx7lLi6++PMEajgeEw\ngd4wHQYDVR0OBBYEFJFU9l4g+PqY088jQNPLPfVk8I3xMB8GA1UdIwQYMBaAFJFU\n9l4g+PqY088jQNPLPfVk8I3xMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQD\nAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBcBgNVHREEVTBThwTA\nqAEJghx0bHNjYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghx0bHNjYTEtZGlzdGls\nbGVyeS1zdXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw\nRQIhANQFOGnkrraLiQU9TKu46o0I8INlYvgjbQyclGdlGpBpAiBCDgE9a9cS75+Q\nMB1wIOEZP882UEU1Kc5q69j9+UHHZw==\n-----END CERTIFICATE-----"
  "peer2.distillery.supply.com":
    "url": "grpcs://peer2.distillery.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer2.distillery.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC4jCCAoigAwIBAgIUYGvCbUW+jyvuRR5EIOjgAH4a+I8wCgYIKoZIzj0EAwIw\nfzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xJTAjBgNV\nBAMMHHRsc2NhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwNDI3MDk1MjQ4\nWhcNMzIwNDI0MDk1MjQ4WjB/MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGgg\nQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnku\nc3VwcGx5LmNvbTElMCMGA1UEAwwcdGxzY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNv\nbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDE0EjSWmnNu6eaoVtIZ9P0eUucJ\n3MAHkwpx17ltjgXJcJ5UVgcJ7cjzuavxB/AS+kLblf/ajwGx7lLi6++PMEajgeEw\ngd4wHQYDVR0OBBYEFJFU9l4g+PqY088jQNPLPfVk8I3xMB8GA1UdIwQYMBaAFJFU\n9l4g+PqY088jQNPLPfVk8I3xMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQD\nAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBcBgNVHREEVTBThwTA\nqAEJghx0bHNjYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghx0bHNjYTEtZGlzdGls\nbGVyeS1zdXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw\nRQIhANQFOGnkrraLiQU9TKu46o0I8INlYvgjbQyclGdlGpBpAiBCDgE9a9cS75+Q\nMB1wIOEZP882UEU1Kc5q69j9+UHHZw==\n-----END CERTIFICATE-----"
  "peer1.producer1.supply.com":
    "url": "grpcs://peer1.producer1.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer1.producer1.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC3DCCAoKgAwIBAgIUKejFqy6SPtXwygkEK083Pzl5ACswCgYIKoZIzj0EAwIw\nfTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5LmNvbTEkMCIGA1UE\nAwwbdGxzY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMB4XDTIyMDQyNzA5NTMyNFoX\nDTMyMDQyNDA5NTMyNFowfTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENh\ncm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3Vw\ncGx5LmNvbTEkMCIGA1UEAwwbdGxzY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXqogIob/bIvLch6igouwpi8XsXhH6Kty\nEyki3SRqoybhgnQ4z0cp5FvTMqGaVwm5px++yYTyklPllSYAsj55EaOB3zCB3DAd\nBgNVHQ4EFgQUGrF6r6WXhLsJuPwiJUR0X6deO7EwHwYDVR0jBBgwFoAUGrF6r6WX\nhLsJuPwiJUR0X6deO7EwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYw\nHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMFoGA1UdEQRTMFGHBMCoAQmC\nG3Rsc2NhMS5wcm9kdWNlcjEuc3VwcGx5LmNvbYIbdGxzY2ExLXByb2R1Y2VyMS1z\ndXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIhAIuJ\nfr+NXgYP9EwttV6xUj7qVyVfNDpQrqvyexTC4YqTAiBSKG0JwNmsvHu1qE98AWjL\nAAMY57NePc+SE8X1o7rqRw==\n-----END CERTIFICATE-----"

"certificateAuthorities":
  "ca1.distillery.supply.com":
    "url": "https://ca1.distillery.supply.com:7054"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC1zCCAnygAwIBAgIUThIi8Te0bmB4khBGmF47zdOOUqkwCgYIKoZIzj0EAwIw\nfDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xIjAgBgNV\nBAMMGWNhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwNDI3MDk1MjQ3WhcN\nMzIwNDI0MDk1MjQ3WjB8MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fy\nb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnkuc3Vw\ncGx5LmNvbTEiMCAGA1UEAwwZY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABEQntiUwEHh8KRi3n1p2Dtplb8VpSajK9p7H\nn+5WVMAT/NUsRtKNBF7e/QdZDFkXGc+1shjzH8qfD7oyxFEMauijgdswgdgwHQYD\nVR0OBBYEFEANCg2izSTDKeBLC6eQjV0lIi1OMB8GA1UdIwQYMBaAFEANCg2izSTD\nKeBLC6eQjV0lIi1OMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBWBgNVHREETzBNhwTAqAEJghlj\nYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghljYTEtZGlzdGlsbGVyeS1zdXBwbHkt\nY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSQAwRgIhAO/Z+zvAC59e\n5kMaHsmw9nChW5u1YAoarv9ACFpJ67/zAiEAhPZ05Rhh0fISCsFisE2xFIc1VuSq\nbXCnYCWCs9qauhY=\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
  "ca1.producer1.supply.com":
    "url": "https://ca1.producer1.supply.com:7054"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICzzCCAnagAwIBAgIUa9YnhLubSM7MELahqQalujcDxiEwCgYIKoZIzj0EAwIw\nejELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5LmNvbTEhMB8GA1UE\nAwwYY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMB4XDTIyMDQyNzA5NTMyNFoXDTMy\nMDQyNDA5NTMyNFowejELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9s\naW5hMRAwDgYDVQQHDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5\nLmNvbTEhMB8GA1UEAwwYY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAEOJBWr4WiCFbNq2knOKsls2eujVvUfnQ1iqtAShLB\nPXAx0bQ1I/lZNoGve8FBw9xh0mjEhezsa2Iiz6AZDIq7+KOB2TCB1jAdBgNVHQ4E\nFgQU8KWnBAJWzHzM4C8Nu9SRcOoZmHYwHwYDVR0jBBgwFoAU8KWnBAJWzHzM4C8N\nu9SRcOoZmHYwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l\nBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMFQGA1UdEQRNMEuHBMCoAQmCGGNhMS5w\ncm9kdWNlcjEuc3VwcGx5LmNvbYIYY2ExLXByb2R1Y2VyMS1zdXBwbHktY29tggls\nb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDRwAwRAIgPVELoAWGAQLB8Wk872me\nE97Q8iCSiN/DpogZ7vyQDXUCIBdWCN9TISpqVVKqCRC4n1F9A2fv70/EwR9a5O+y\nu7If\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
