---
OrdererOrgs:
  - Name: supply.com
    Domain: supply.com
    Specs:
      - Hostname: orderer1
        SANS:
          - 10.1.10.24
      - Hostname: orderer2
        SANS:
          - 10.1.10.24
      - Hostname: orderer3
        SANS:
          - 10.1.10.24

PeerOrgs:
  - Name: distillery.supply.com
    Domain: distillery.supply.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.distillery.supply.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.distillery.supply.com
        SANS:
          - 10.1.10.24
      - Hostname: peer2
        CommonName: peer2.distillery.supply.com
        SANS:
          - 10.1.10.24
  - Name: shop.supply.com
    Domain: shop.supply.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.shop.supply.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.shop.supply.com
        SANS:
          - 10.1.10.24
      - Hostname: peer2
        CommonName: peer2.shop.supply.com
        SANS:
          - 10.1.10.24
  - Name: supplier.supply.com
    Domain: supplier.supply.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.supplier.supply.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.supplier.supply.com
        SANS:
          - 10.1.10.24
      - Hostname: peer2
        CommonName: peer2.supplier.supply.com
        SANS:
          - 10.1.10.24
