---
OrdererOrgs:
  - Name: supply.com
    Domain: supply.com
    Specs:
      - Hostname: orderer1
        SANS:
          - orderer1.supply.com
      - Hostname: orderer2
        SANS:
          - orderer2.supply.com
      - Hostname: orderer3
        SANS:
          - orderer3.supply.com

PeerOrgs:
  - Name: distillery.supply.com
    Domain: distillery.supply.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.distillery.supply.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.distillery.supply.com
        SANS:
          - peer1.distillery.supply.com
      - Hostname: peer2
        CommonName: peer2.distillery.supply.com
        SANS:
          - peer2.distillery.supply.com
  - Name: producer1.supply.com
    Domain: producer1.supply.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.producer1.supply.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.producer1.supply.com
        SANS:
          - peer1.producer1.supply.com
