---
"name": "fabric-network"
"x-type": "hlfv1"
"version": "1.0.0"
"channels":
  "supplychain":
    "orderers":
    - "orderer1.supply.com"
    - "orderer2.supply.com"
    - "orderer3.supply.com"
    "peers":
    - "peer1.distillery.supply.com"
    - "peer2.distillery.supply.com"
    - "peer1.producer1.supply.com"
"organizations":
  "distillery.supply.com":
    "mspid": "distillery-supply-com"
    "peers":
    - "peer1.distillery.supply.com"
    - "peer2.distillery.supply.com"
    "orderers": []
    "certificateAuthorities":
    - "ca1.distillery.supply.com"
  "producer1.supply.com":
    "mspid": "producer1-supply-com"
    "peers":
    - "peer1.producer1.supply.com"
    "orderers": []
    "certificateAuthorities":
    - "ca1.producer1.supply.com"
  "supply.com":
    "mspid": "supply-com"
    "peers": []
    "orderers":
    - "orderer1.supply.com"
    - "orderer2.supply.com"
    - "orderer3.supply.com"

"orderers":
  "orderer1.supply.com":
    "url": "grpcs://orderer1.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer1.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICmzCCAkKgAwIBAgIUIBTghZlktmDXGnDs81jD3YhmH5AwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDQyODIxNTcxOFoXDTMyMDQyNTIxNTcxOFowaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECTJdqRd63JN5/et8mG486ZRf\nFz5fVuYPyVGb/RFRnEDp31S5DpsQt7gEY885fp0unZ9FbQ7lJjutOxakX1OND6OB\nyTCBxjAdBgNVHQ4EFgQUph6GIx4a14BVfYyfCJ2y5J8M/fYwHwYDVR0jBBgwFoAU\nph6GIx4a14BVfYyfCJ2y5J8M/fYwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQmCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNHADBEAiAE6790evWSr0/zhbt9bLhWGcFv\n56RZP9xIUckAG4tyVgIgRRB+ZJWEqYU8EkI6amgAQpilaOMTEtahUMkRLWOluiI=\n-----END CERTIFICATE-----"
  "orderer2.supply.com":
    "url": "grpcs://orderer2.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer2.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICmzCCAkKgAwIBAgIUIBTghZlktmDXGnDs81jD3YhmH5AwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDQyODIxNTcxOFoXDTMyMDQyNTIxNTcxOFowaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECTJdqRd63JN5/et8mG486ZRf\nFz5fVuYPyVGb/RFRnEDp31S5DpsQt7gEY885fp0unZ9FbQ7lJjutOxakX1OND6OB\nyTCBxjAdBgNVHQ4EFgQUph6GIx4a14BVfYyfCJ2y5J8M/fYwHwYDVR0jBBgwFoAU\nph6GIx4a14BVfYyfCJ2y5J8M/fYwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQmCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNHADBEAiAE6790evWSr0/zhbt9bLhWGcFv\n56RZP9xIUckAG4tyVgIgRRB+ZJWEqYU8EkI6amgAQpilaOMTEtahUMkRLWOluiI=\n-----END CERTIFICATE-----"
  "orderer3.supply.com":
    "url": "grpcs://orderer3.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer3.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICmzCCAkKgAwIBAgIUIBTghZlktmDXGnDs81jD3YhmH5AwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDQyODIxNTcxOFoXDTMyMDQyNTIxNTcxOFowaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECTJdqRd63JN5/et8mG486ZRf\nFz5fVuYPyVGb/RFRnEDp31S5DpsQt7gEY885fp0unZ9FbQ7lJjutOxakX1OND6OB\nyTCBxjAdBgNVHQ4EFgQUph6GIx4a14BVfYyfCJ2y5J8M/fYwHwYDVR0jBBgwFoAU\nph6GIx4a14BVfYyfCJ2y5J8M/fYwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQmCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNHADBEAiAE6790evWSr0/zhbt9bLhWGcFv\n56RZP9xIUckAG4tyVgIgRRB+ZJWEqYU8EkI6amgAQpilaOMTEtahUMkRLWOluiI=\n-----END CERTIFICATE-----"

"peers":
  "peer1.distillery.supply.com":
    "url": "grpcs://peer1.distillery.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer1.distillery.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC4zCCAoigAwIBAgIUI88mCHpZzK3HCQ4PDcuHPe/gUd4wCgYIKoZIzj0EAwIw\nfzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xJTAjBgNV\nBAMMHHRsc2NhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwNDI4MjE1NjI2\nWhcNMzIwNDI1MjE1NjI2WjB/MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGgg\nQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnku\nc3VwcGx5LmNvbTElMCMGA1UEAwwcdGxzY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNv\nbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFzcka13+5J4YxHwQgompeQdg1ad\nxz7fNLy96rDLIfah6iLN09q+bs29ocJR7MKxAKtAfUCjCqQ1D17QMK6RHoqjgeEw\ngd4wHQYDVR0OBBYEFJvvz7Uky1wMAvOpG6ohXztI9j2UMB8GA1UdIwQYMBaAFJvv\nz7Uky1wMAvOpG6ohXztI9j2UMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQD\nAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBcBgNVHREEVTBThwTA\nqAEJghx0bHNjYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghx0bHNjYTEtZGlzdGls\nbGVyeS1zdXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSQAw\nRgIhAIqB+/1DA4wMKLkMasmOFWFrJJn8lWD++glKKyNn5dLqAiEAneV37OPL5Yfi\nMJo9g41g13gViOcjLzSdN6gKKrPNX7Y=\n-----END CERTIFICATE-----"
  "peer2.distillery.supply.com":
    "url": "grpcs://peer2.distillery.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer2.distillery.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC4zCCAoigAwIBAgIUI88mCHpZzK3HCQ4PDcuHPe/gUd4wCgYIKoZIzj0EAwIw\nfzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xJTAjBgNV\nBAMMHHRsc2NhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwNDI4MjE1NjI2\nWhcNMzIwNDI1MjE1NjI2WjB/MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGgg\nQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnku\nc3VwcGx5LmNvbTElMCMGA1UEAwwcdGxzY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNv\nbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFzcka13+5J4YxHwQgompeQdg1ad\nxz7fNLy96rDLIfah6iLN09q+bs29ocJR7MKxAKtAfUCjCqQ1D17QMK6RHoqjgeEw\ngd4wHQYDVR0OBBYEFJvvz7Uky1wMAvOpG6ohXztI9j2UMB8GA1UdIwQYMBaAFJvv\nz7Uky1wMAvOpG6ohXztI9j2UMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQD\nAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBcBgNVHREEVTBThwTA\nqAEJghx0bHNjYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghx0bHNjYTEtZGlzdGls\nbGVyeS1zdXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSQAw\nRgIhAIqB+/1DA4wMKLkMasmOFWFrJJn8lWD++glKKyNn5dLqAiEAneV37OPL5Yfi\nMJo9g41g13gViOcjLzSdN6gKKrPNX7Y=\n-----END CERTIFICATE-----"
  "peer1.producer1.supply.com":
    "url": "grpcs://peer1.producer1.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer1.producer1.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC3DCCAoKgAwIBAgIUOkzqSltCdJuviiP/zIxPf+cIPqgwCgYIKoZIzj0EAwIw\nfTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5LmNvbTEkMCIGA1UE\nAwwbdGxzY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMB4XDTIyMDQyODIxNTY1NloX\nDTMyMDQyNTIxNTY1NlowfTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENh\ncm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3Vw\ncGx5LmNvbTEkMCIGA1UEAwwbdGxzY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGwSIHxH8o+LigKmZSGfQgYwaFBljXbwe\nCDvDLzKwnPH5JYxE8jRQWuAzuiNt28QZG1YyXbgZFvohmbwhdmQu9qOB3zCB3DAd\nBgNVHQ4EFgQUcn9mjNs415ySG0XnIfOTBL/ZnU0wHwYDVR0jBBgwFoAUcn9mjNs4\n15ySG0XnIfOTBL/ZnU0wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYw\nHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMFoGA1UdEQRTMFGHBMCoAQmC\nG3Rsc2NhMS5wcm9kdWNlcjEuc3VwcGx5LmNvbYIbdGxzY2ExLXByb2R1Y2VyMS1z\ndXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIgC6bL\nlgqQmotwdKocSsqvpdlNOQty4PoV/zd9PWMReJ4CIQCDyr1yKpO4qacxqvF8rcqb\n+Na78pg2PQ53ULwiydHJig==\n-----END CERTIFICATE-----"

"certificateAuthorities":
  "ca1.distillery.supply.com":
    "url": "https://ca1.distillery.supply.com:7054"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC1zCCAnygAwIBAgIUEeUHZltU/WQp5Spk4uaYETp8B4MwCgYIKoZIzj0EAwIw\nfDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xIjAgBgNV\nBAMMGWNhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwNDI4MjE1NjI2WhcN\nMzIwNDI1MjE1NjI2WjB8MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fy\nb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnkuc3Vw\ncGx5LmNvbTEiMCAGA1UEAwwZY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABKR8Z369h9P2GHTLcmW9Rew78nll+x0cS9ME\nBsuYfNWBbE4Srvdi8Ax03GfJT4+X8NULb5qvFV2w5GU6VDSskWijgdswgdgwHQYD\nVR0OBBYEFNWihwzfvgeIer/czY+FMwgg3pKBMB8GA1UdIwQYMBaAFNWihwzfvgeI\ner/czY+FMwgg3pKBMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBWBgNVHREETzBNhwTAqAEJghlj\nYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghljYTEtZGlzdGlsbGVyeS1zdXBwbHkt\nY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSQAwRgIhAJ5r5NKhVoY7\nAgvF5rPzhCz0cyn0IIQ35eV7IR4faOccAiEA3Dd1j2M2to7LxHSTr8rMcNEkdukV\n9DjlSc2lEfV0bx0=\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
  "ca1.producer1.supply.com":
    "url": "https://ca1.producer1.supply.com:7054"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC0DCCAnagAwIBAgIUClnMV5COq0oe3lBKN5Y+L1UoHJ8wCgYIKoZIzj0EAwIw\nejELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5LmNvbTEhMB8GA1UE\nAwwYY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMB4XDTIyMDQyODIxNTY1NloXDTMy\nMDQyNTIxNTY1NlowejELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9s\naW5hMRAwDgYDVQQHDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5\nLmNvbTEhMB8GA1UEAwwYY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAEHuEUuKKejzlkYH+5SUzZ0g6RH3x5wOiP+MCqZesp\nbJD0gIfkNX3Wvgjr0LGGw9XO9P/4XbcSW2jSNeflz5s2xaOB2TCB1jAdBgNVHQ4E\nFgQUfF5DRWgyKNNyVA01VCoR+f0tB3wwHwYDVR0jBBgwFoAUfF5DRWgyKNNyVA01\nVCoR+f0tB3wwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l\nBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMFQGA1UdEQRNMEuHBMCoAQmCGGNhMS5w\ncm9kdWNlcjEuc3VwcGx5LmNvbYIYY2ExLXByb2R1Y2VyMS1zdXBwbHktY29tggls\nb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIgUA50xbfMEJtG9VSOHs00\n/HpDuQ798zocApEZ0EJm4UICIQDjdaVbXAV04zE5Lk4AIMeSdWKCPF3XJXjOGQco\n+RvM9g==\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
