---
"name": "fabric-network"
"x-type": "hlfv1"
"version": "1.0.0"
"channels":
  "supplychain":
    "orderers":
    - "orderer1.supply.com"
    - "orderer2.supply.com"
    - "orderer3.supply.com"
    "peers":
    - "peer1.distillery.supply.com"
    - "peer2.distillery.supply.com"
    - "peer1.producer1.supply.com"
"organizations":
  "distillery.supply.com":
    "mspid": "distillery-supply-com"
    "peers":
    - "peer1.distillery.supply.com"
    - "peer2.distillery.supply.com"
    "orderers": []
    "certificateAuthorities":
    - "ca1.distillery.supply.com"
  "producer1.supply.com":
    "mspid": "producer1-supply-com"
    "peers":
    - "peer1.producer1.supply.com"
    "orderers": []
    "certificateAuthorities":
    - "ca1.producer1.supply.com"
  "supply.com":
    "mspid": "supply-com"
    "peers": []
    "orderers":
    - "orderer1.supply.com"
    - "orderer2.supply.com"
    - "orderer3.supply.com"

"orderers":
  "orderer1.supply.com":
    "url": "grpcs://orderer1.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer1.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICnDCCAkKgAwIBAgIUDuOk9JY8awYzbnFw34L/iCHoGfgwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDkxMzA5MTMzN1oXDTMyMDkxMDA5MTMzN1owaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhVtKjKFjrH4GiTvvqyFhlPaJ\nQlQIAFe7HIemxdeqNnHslAyuGaWwfTtKm+L8nR3yloGH3rKvi247eS2N5YFzMqOB\nyTCBxjAdBgNVHQ4EFgQUpgJUSAYzO9NhxH4VTEE/zwa51IYwHwYDVR0jBBgwFoAU\npgJUSAYzO9NhxH4VTEE/zwa51IYwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQaCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiEA75XCFq6I9jJVghNNyjYrZohC\ngSFpKYB9tRCHG5lcrcsCIErO2cTMNM1Y4+tEio2tNR/kRKez0wpdVS6gstJhQvXT\n-----END CERTIFICATE-----"
  "orderer2.supply.com":
    "url": "grpcs://orderer2.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer2.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICnDCCAkKgAwIBAgIUDuOk9JY8awYzbnFw34L/iCHoGfgwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDkxMzA5MTMzN1oXDTMyMDkxMDA5MTMzN1owaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhVtKjKFjrH4GiTvvqyFhlPaJ\nQlQIAFe7HIemxdeqNnHslAyuGaWwfTtKm+L8nR3yloGH3rKvi247eS2N5YFzMqOB\nyTCBxjAdBgNVHQ4EFgQUpgJUSAYzO9NhxH4VTEE/zwa51IYwHwYDVR0jBBgwFoAU\npgJUSAYzO9NhxH4VTEE/zwa51IYwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQaCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiEA75XCFq6I9jJVghNNyjYrZohC\ngSFpKYB9tRCHG5lcrcsCIErO2cTMNM1Y4+tEio2tNR/kRKez0wpdVS6gstJhQvXT\n-----END CERTIFICATE-----"
  "orderer3.supply.com":
    "url": "grpcs://orderer3.supply.com:7050"
    "grpcOptions":
      "ssl-target-name-override": "orderer3.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICnDCCAkKgAwIBAgIUDuOk9JY8awYzbnFw34L/iCHoGfgwCgYIKoZIzj0EAwIw\naDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5z\ndXBwbHkuY29tMB4XDTIyMDkxMzA5MTMzN1oXDTMyMDkxMDA5MTMzN1owaDELMAkG\nA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl\naWdoMRMwEQYDVQQKDApzdXBwbHkuY29tMRkwFwYDVQQDDBB0bHNjYS5zdXBwbHku\nY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhVtKjKFjrH4GiTvvqyFhlPaJ\nQlQIAFe7HIemxdeqNnHslAyuGaWwfTtKm+L8nR3yloGH3rKvi247eS2N5YFzMqOB\nyTCBxjAdBgNVHQ4EFgQUpgJUSAYzO9NhxH4VTEE/zwa51IYwHwYDVR0jBBgwFoAU\npgJUSAYzO9NhxH4VTEE/zwa51IYwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\nBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEQGA1UdEQQ9MDuH\nBMCoAQaCEHRsc2NhLnN1cHBseS5jb22CEHRsc2NhLXN1cHBseS1jb22CCWxvY2Fs\naG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiEA75XCFq6I9jJVghNNyjYrZohC\ngSFpKYB9tRCHG5lcrcsCIErO2cTMNM1Y4+tEio2tNR/kRKez0wpdVS6gstJhQvXT\n-----END CERTIFICATE-----"

"peers":
  "peer1.distillery.supply.com":
    "url": "grpcs://peer1.distillery.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer1.distillery.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC4TCCAoigAwIBAgIUFJlWV+jXdaS96WVFfyfto77CERMwCgYIKoZIzj0EAwIw\nfzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xJTAjBgNV\nBAMMHHRsc2NhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwOTEzMDkxMjMz\nWhcNMzIwOTEwMDkxMjMzWjB/MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGgg\nQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnku\nc3VwcGx5LmNvbTElMCMGA1UEAwwcdGxzY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNv\nbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIZrU3qPOHDyKeJXwjLfprt1BQkC\n0Q5Vz+Z4kbxVfkB8eyGAI4FjZEdGdluo6UMcO1HdWSg9RKT6HeLDHm9l4LijgeEw\ngd4wHQYDVR0OBBYEFAwA3bu13agcFmfPWh+mvAmVZjp0MB8GA1UdIwQYMBaAFAwA\n3bu13agcFmfPWh+mvAmVZjp0MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQD\nAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBcBgNVHREEVTBThwTA\nqAEGghx0bHNjYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghx0bHNjYTEtZGlzdGls\nbGVyeS1zdXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDRwAw\nRAIgIezAGyr+2SKvFzVEgtEfHi5X39SYle8uhavoQbtdMZMCIAvB+15uysiAnhSq\nws1v51GxNOIRUsh/8szgUeKgz3qM\n-----END CERTIFICATE-----"
  "peer2.distillery.supply.com":
    "url": "grpcs://peer2.distillery.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer2.distillery.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC4TCCAoigAwIBAgIUFJlWV+jXdaS96WVFfyfto77CERMwCgYIKoZIzj0EAwIw\nfzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xJTAjBgNV\nBAMMHHRsc2NhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwOTEzMDkxMjMz\nWhcNMzIwOTEwMDkxMjMzWjB/MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGgg\nQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnku\nc3VwcGx5LmNvbTElMCMGA1UEAwwcdGxzY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNv\nbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIZrU3qPOHDyKeJXwjLfprt1BQkC\n0Q5Vz+Z4kbxVfkB8eyGAI4FjZEdGdluo6UMcO1HdWSg9RKT6HeLDHm9l4LijgeEw\ngd4wHQYDVR0OBBYEFAwA3bu13agcFmfPWh+mvAmVZjp0MB8GA1UdIwQYMBaAFAwA\n3bu13agcFmfPWh+mvAmVZjp0MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQD\nAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBcBgNVHREEVTBThwTA\nqAEGghx0bHNjYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghx0bHNjYTEtZGlzdGls\nbGVyeS1zdXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDRwAw\nRAIgIezAGyr+2SKvFzVEgtEfHi5X39SYle8uhavoQbtdMZMCIAvB+15uysiAnhSq\nws1v51GxNOIRUsh/8szgUeKgz3qM\n-----END CERTIFICATE-----"
  "peer1.producer1.supply.com":
    "url": "grpcs://peer1.producer1.supply.com:7051"
    "grpcOptions":
      "ssl-target-name-override": "peer1.producer1.supply.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC3DCCAoKgAwIBAgIUFfVbskKoy6zsaI8x3mVGNMUjCqgwCgYIKoZIzj0EAwIw\nfTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5LmNvbTEkMCIGA1UE\nAwwbdGxzY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMB4XDTIyMDkxMzA5MTMxMloX\nDTMyMDkxMDA5MTMxMlowfTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENh\ncm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3Vw\ncGx5LmNvbTEkMCIGA1UEAwwbdGxzY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMFkw\nEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEmtaWmO9dpUu3x+yZlOpub6SDCd6KrPaT\nQFwkkxvKFjgQHpcJaMpgz4YcOKLEYOFNzDMTlpRpV1wwJlAYSy6gQaOB3zCB3DAd\nBgNVHQ4EFgQUkFH1Vu9QkHVXLAwfxT6Y6H8Q9WwwHwYDVR0jBBgwFoAUkFH1Vu9Q\nkHVXLAwfxT6Y6H8Q9WwwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYw\nHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMFoGA1UdEQRTMFGHBMCoAQaC\nG3Rsc2NhMS5wcm9kdWNlcjEuc3VwcGx5LmNvbYIbdGxzY2ExLXByb2R1Y2VyMS1z\ndXBwbHktY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIhANMy\ngXZfTcFNaB4yjmcE4lZveh/nHxI1Dzf5G+x002eVAiAJ5q3+V1XYSICUF3pViQ94\nObrsDyBEAsEuXYjUVvs+sA==\n-----END CERTIFICATE-----"

"certificateAuthorities":
  "ca1.distillery.supply.com":
    "url": "https://ca1.distillery.supply.com:7054"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC1TCCAnygAwIBAgIUOa8+P1at1cpTu9R0cdxfPcUxldEwCgYIKoZIzj0EAwIw\nfDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR4wHAYDVQQKDBVkaXN0aWxsZXJ5LnN1cHBseS5jb20xIjAgBgNV\nBAMMGWNhMS5kaXN0aWxsZXJ5LnN1cHBseS5jb20wHhcNMjIwOTEzMDkxMjMzWhcN\nMzIwOTEwMDkxMjMzWjB8MQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fy\nb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gxHjAcBgNVBAoMFWRpc3RpbGxlcnkuc3Vw\ncGx5LmNvbTEiMCAGA1UEAwwZY2ExLmRpc3RpbGxlcnkuc3VwcGx5LmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABBgEPX3zOd4CE45hFuWBmco9lcJCnxpF0fhv\nJknMwU4i2e+RlQiphn865f1acfVQMnvrn4EIV+SLtO7q8Cw74JejgdswgdgwHQYD\nVR0OBBYEFFDaBafwX6M5dwGnpZ7imIRK4UQYMB8GA1UdIwQYMBaAFFDaBafwX6M5\ndwGnpZ7imIRK4UQYMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBWBgNVHREETzBNhwTAqAEGghlj\nYTEuZGlzdGlsbGVyeS5zdXBwbHkuY29tghljYTEtZGlzdGlsbGVyeS1zdXBwbHkt\nY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDRwAwRAIgMcT6oIBEXnPO\nae0Hu42mfPzC0jkTfHTjYV4ZLoOBR/8CIGeTSS0fZvqLqPA73WPahmV1v32dpuSd\nJMjRd8fdpREW\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
  "ca1.producer1.supply.com":
    "url": "https://ca1.producer1.supply.com:7054"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIIC0TCCAnagAwIBAgIUT6peNHBu+EaRHhK+HWfxZwNUdW4wCgYIKoZIzj0EAwIw\nejELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5LmNvbTEhMB8GA1UE\nAwwYY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMB4XDTIyMDkxMzA5MTMxMloXDTMy\nMDkxMDA5MTMxMlowejELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9s\naW5hMRAwDgYDVQQHDAdSYWxlaWdoMR0wGwYDVQQKDBRwcm9kdWNlcjEuc3VwcGx5\nLmNvbTEhMB8GA1UEAwwYY2ExLnByb2R1Y2VyMS5zdXBwbHkuY29tMFkwEwYHKoZI\nzj0CAQYIKoZIzj0DAQcDQgAEwBdV5G5CJcqGyTGJ3NQAQQQD6QTymNdK76bPq3l7\nrOmZmGNDT46xUh9AZzjAg5zpYxlgn1c1ZfOMbqgGevcCq6OB2TCB1jAdBgNVHQ4E\nFgQUSQt/IV7Msv4AE/lCuLo8c45pBfgwHwYDVR0jBBgwFoAUSQt/IV7Msv4AE/lC\nuLo8c45pBfgwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l\nBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMFQGA1UdEQRNMEuHBMCoAQaCGGNhMS5w\ncm9kdWNlcjEuc3VwcGx5LmNvbYIYY2ExLXByb2R1Y2VyMS1zdXBwbHktY29tggls\nb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSQAwRgIhANn+B+xfGLZIU5ThJE9n\nGhuhvaBr6k0hv2X9XtHigSZ+AiEAtFPJqjx8E/Oy+1H73xxUYonJbALRexNAsfFP\ng06Q/fQ=\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
