version: '3'
services:
    splunk.supply.com:
        container_name: splunk.supply.com
        image: splunk/splunk:8.1
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_PASSWORD=changeme
            - SPLUNK_HEC_TOKEN=00000000-0000-0000-0000-000000000000
            - SPLUNK_APPS_URL=http://s3.amazonaws.com/splunk-hyperledger/status-indicator-custom-visualization_130.tgz,https://github.com/splunkdlt/splunk-hyperledger-fabric/releases/download/2.0.2/splunk-hyperledger-fabric-v2.0.2.tgz
        ports:
            - '8000:8000'
            - '8088:8088'
        volumes:
            - ./splunk.yml:/tmp/defaults/default.yml
    fabric-logger.supply.com:
        restart: always
        depends_on:
            - splunk.supply.com
        container_name: fabric-logger.supply.com
        image: ghcr.io/splunkdlt/fabric-logger:latest
        volumes:
            - ./network-config.yml:/tmp/network-config.yml
            - ../vars/keyfiles:/crypto-config
            - ./fabriclogger.yml:/tmp/fabriclogger.yml
        environment:
            - FABRIC_KEYFILE=/crypto-config/peerOrganizations/distillery.supply.com/users/Admin@distillery.supply.com/msp/keystore/priv_sk
            - FABRIC_CERTFILE=/crypto-config/peerOrganizations/distillery.supply.com/users/Admin@distillery.supply.com/msp/signcerts/Admin@distillery.supply.com-cert.pem
            - FABRIC_CLIENT_KEYFILE=/crypto-config/peerOrganizations/distillery.supply.com/peers/peer1.distillery.supply.com/tls/server.key
            - FABRIC_CLIENT_CERTFILE=/crypto-config/peerOrganizations/distillery.supply.com/peers/peer1.distillery.supply.com/tls/server.crt
            - FABRIC_MSP=distillery-supply-com
            - FABRIC_LOGGER_USERNAME=Admin
            - FABRIC_PEER=peer1.distillery.supply.com
            - NETWORK_CONFIG=/tmp/network-config.yml
            - SPLUNK_HEC_TOKEN=00000000-0000-0000-0000-000000000000
            - SPLUNK_HEC_URL=https://splunk.supply.com:8088
            - SPLUNK_INDEX=hyperledger_logs
            - SPLUNK_METRICS_INDEX=hyperledger_metrics
            - SPLUNK_HEC_REJECT_INVALID_CERTS=false
            - FABRIC_LOGGER_CONFIG=/tmp/fabriclogger.yml
            - PROMETHEUS_DISCOVERY=true
            - PROMETHEUS_ORDERER_PORT=7060
            - PROMETHEUS_PEER_PORT=7061

networks:
    default:
        external:
            name: supplychain
